import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Header } from "@/_components/Header";
import { Footer } from "@/_components/Footer";
import DarkModeProvider from "@/_components/DarkModeContext";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <DarkModeProvider>
        <body
          className={`${inter.className} flex h-screen flex-col dark:bg-slate-900 dark:text-slate-200`}
        >
          <Header></Header>
          {children}
          <Footer></Footer>
        </body>
      </DarkModeProvider>
    </html>
  );
}
